version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-app
    working_dir: /app/project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/project:/app/project:cached
      - /app/project/node_modules

